#!/bin/bash

usage() {
    echo "Usage: $0 [-h] [-r web_root] [-p port]"
}

source $(dirname $0)/config.sh

while getopts ":hr:p:" opt; do
    case $opt in
        r)
            root_path=$OPTARG
            ;;
        p)
            port=$OPTARG
            ;;
        h | *)
            usage
            exit 0
            ;;
    esac
done

eval "nc -lkp $port -e \"./serv -r $root_path\""
