#!/bin/bash


load_config() {
#loads configuration file at config.sh or creates a default one and a default 404 page if they don't exist
    if [[ ! -f "config.sh" ]]; then
        if [[ ! -f "404.html" ]]; then
            { cat > 404.html <<EOF
<!DOCTYPE html>
<html>
    <head>
        <title>Not found</title>
    </head>
    <body>
        <h1>Resource not found</h1>
    </body>
</html>
EOF
            }
        fi
        { cat > config.sh <<EOF
#server port
port=1234
#root directory
root_path="./"
#404 page location
not_found_page="404.html"
#request parameters log files
get_log_file="get_log"
post_log_file="post_log"
#files forbidden from access
forbidden_files=("serv config.sh \$get_log_file \$post_log_file")
#rewriting paths to resources
declare -A REWRITE=( [/]=/index.html )
EOF
        }
    fi
}

read_request() {
    read request_text
#    request_text=""
#    while read line ; do
#        request_text+="$line \n"
#        [ -z "$line" ] && break
#    done
}

declare -A REQUEST
parse_request() {
    #parses the request text to associative table and changes the resource according to REWRITE and creates a path to resource
    REQUEST[resource]=$(echo $request_text | cut -d " " -f 2 | cut -d "?" -f 1)
    for path in ${!REWRITE[@]}; do
        if [[ "${REQUEST[resource]}" == $path ]]; then
            REQUEST[resource]=${REWRITE[$path]}
            break
        fi
    done
    REQUEST[resource]=$(echo ${REQUEST[resource]} | sed -e s#/#$root_path#)
    REQUEST[method]=$(echo $request_text | cut -d " " -f 1) 
    if [[ ${REQUEST[method]} == "GET" ]]; then
        parse_get_params
    elif [[ ${REQUEST[method]} == "POST" ]]; then
        REQUEST[content-type]=$(echo $request_text | grep "Content-Type" | cut -d ":" -f 2 | cut -d " " -f 2)
        parse_post_params
    fi
}

parse_get_params() {
    #parses parameters given in GET request
    if [[ $request_text == *"?"* ]]; then
        declare -A GET
        get_params=$(echo $request_text | cut -d " " -f 2 | cut -d "?" -f 2 | tr "&" "\n")
        for param in $get_params; do
            GET[$(echo $param | cut -d "=" -f 1)]=$(echo $param | cut -d "=" -f 2)
        done
        handle_get_params
    fi
}

handle_get_params() {
    #logs GET parameters to log file
    echo "" >> $get_log_file
    for key in "${!GET[@]}"; do
        echo -e "$key : ${GET[$key]}" >> $get_log_file
    done
}

parse_post_params() {
    declare -A POST
    #TODO
}

construct_response_headers() {
    #creates response headers and checks wheather the requested resource exists (file_found flag)
    if [[ -f ${REQUEST[resource]} ]]; then
        response_text="HTTP/1.1 200 OK\n";
        response_text+="Connection: Keep-Alive\n";
        response_text+="Content-Length: $(stat -c'%s' ${REQUEST[resource]})\n"
        if [[ $(echo ${REQUEST[resource]##*.}) == "css" ]]; then
            response_text+="Content-Type: text/css\n"
        elif [[ $(echo ${REQUEST[resource]##*.}) == "js" ]]; then
            response_text+="Content-Type: text/javascript\n"
        else
            response_text+="Content-Type: $(file -b --mime-type ${REQUEST[resource]})\n"
        fi
        response_text+="\n"
        #response_text+=$(tr -d '\0' <${REQUEST[resource]})
        file_found=1
    else
        response_text="HTTP/1.1 404 Not found\n"
        response_text+="Content-Type: text/html\n"
        #response_text+=$(tr -d '\0' <$not_found_page)
        file_found=0
    fi
}

send_response() {
    #echoes the response headers and the resources content
    echo -e $response_text
    if [[ $file_found -eq 1 ]]; then
        filename=${REQUEST[resource]};
    else
        filename=$not_found_page;
    fi

    while read line; do
        echo "$line"
    done < $filename
}

load_config
source $(dirname $0)/config.sh

read_request
parse_request

#debug part
echo $request_text >> request_log
#end of debug

construct_response_headers
send_response
