#!/bin/bash

load_config() {
#loads configuration file at config.sh or creates a default one and a default 404 page if they don't exist
    if [[ ! -f "config.sh" ]]; then
        if [[ ! -f "404.html" ]]; then
            { cat > 404.html <<EOF
<html>
    <head>
        <title>Not found</title>
    </head>
    <body>
        <h1>Resource not found</h1>
    </body>
</html>
EOF
            }
        fi
        { cat > config.sh <<EOF
#404 page location
not_found_page="404.html"
EOF
        }
    fi
    source $(dirname $0)/config.sh
}

load_config

read request
resource=$(echo $request | cut -d " " -f 2 | sed s#^/#./#g);
if [[ $(echo $request | cut -d " " -f 1) == "GET" ]]; then
    if [[ -f $resource ]]; then
        echo "HTTP/1.1 200 OK";
        echo -e "Connection: Keep-Alive";
        if [[ $(echo ${resource##*.}) == "html" ]]; then
            echo -e "Content-Type: text/html\n"
        elif [[ $(echo ${resource##*.}) == "css" ]]; then
            echo -e "Content-Type: text/css\n"
        else
            echo -e "Content-Type: $(file -b --mime-type $resource); charset=binary\n"
        fi
        echo $(tr -d '\0' <$resource);
    else
        echo -e "HTTP/1.1 404 Not found"
        echo -e "Content-Type: text/html\n"
        echo -e "`tr -d '\0' <$not_found_page`";
    fi
fi
